version: '3'

services:
  api-server:
    build:
      context: .
    container_name: auth-api-server
    image: auth-api-server
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - '3000:3333'

  nginx-server:
    image: nginx:latest
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api-server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-server
    # command: certonly --webroot --webroot-path=/var/www/html --email rahulranjan@bitwisebeat.tech --agree-tos --no-eff-email --staging -d api.bitwisebeat.tech
    command: certonly --webroot --webroot-path=/var/www/html --email rahulranjan@bitwisebeat.tech --agree-tos --no-eff-email --force-renewal -d api.bitwisebeat.tech

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/fantasty-v2/views
      o: bind

networks:
  app-network:
    driver: bridge
