version: '3'

services:
  api-server:
    build:
      context: .
    container_name: auth-api-server
    image: auth-api-server
    restart: unless-stopped
    env_file:
      - .env
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3000
    #   - MONGODB_URL=mongodb://host.docker.internal:27017/dataforms

    networks:
      - app-network
    ports:
      - '3000:3333'

networks:
  app-network:
    driver: bridge
